import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import "@ant-design/v5-patch-for-react-19";
import { App, ConfigProvider } from "antd";
import { SessionProvider } from "next-auth/react";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<AntdRegistry>
					<SessionProvider>
						<NuqsAdapter>
							<ConfigProvider direction="rtl">
								<App>{children}</App>
							</ConfigProvider>
						</NuqsAdapter>
					</SessionProvider>
				</AntdRegistry>
			</body>
		</html>
	);
}
